name: Cypress Test

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Start application
      run: npm start &
      env:
        CI: true

    - name: Run Cypress test
      run: npm run cypress:run